from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors

from reportlab.lib.styles import getSampleStyleSheet


def create_pdf_report(

    output_path,

    accuracy,

    precision,

    recall,

    f1,

    feature_df

):

    styles = getSampleStyleSheet()

    document = SimpleDocTemplate(

        output_path

    )

    story = []

    story.append(

        Paragraph(

            "ExplainX AI Report",

            styles["Title"]

        )

    )

    story.append(

        Spacer(1, 20)

    )

    story.append(

        Paragraph(

            "Model Performance",

            styles["Heading2"]

        )

    )

    metrics = [

        ["Metric", "Value"],

        ["Accuracy", f"{accuracy:.4f}"],

        ["Precision", f"{precision:.4f}"],

        ["Recall", f"{recall:.4f}"],

        ["F1 Score", f"{f1:.4f}"]

    ]

    table = Table(metrics)

    table.setStyle(

        TableStyle(

            [

                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#8B6B4F")),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

                ("ALIGN", (0, 0), (-1, -1), "CENTER")

            ]

        )

    )

    story.append(table)

    story.append(

        Spacer(1, 20)

    )

    story.append(

        Paragraph(

            "Top 10 Important Features",

            styles["Heading2"]

        )

    )

    feature_table = [["Feature", "Importance"]]

    for _, row in feature_df.head(10).iterrows():

        feature_table.append(

            [

                str(row["Feature"]),

                f"{row['Importance']:.4f}"

            ]

        )

    table2 = Table(feature_table)

    table2.setStyle(

        TableStyle(

            [

                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#A67C52")),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

                ("ALIGN", (0, 0), (-1, -1), "CENTER")

            ]

        )

    )

    story.append(table2)

    story.append(

        Spacer(1, 20)

    )

    story.append(

        Paragraph(

            "Generated by ExplainX AI",

            styles["Italic"]

        )

    )

    document.build(

        story

    )